AllCops:
  Exclude:
    - 'bin/bundle'
    - 'bin/setup'
    - 'config/environments/*'
    - 'db/migrate/*'
    - 'spec/requests/api/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

